version: '3'
services:
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins
        port:
            - "8080:8080"
        volumes:
            - "$PWD/jenkins_home:/var/jenkins_home"
        nerworks:
            - net
    remote_host:
        container_name: remote-host
        image: remote-host
        build:
            context: centos7
        networks: 
            - net
    db_host:
        container_name: mysql-db
        image: mysql:5.7
        environment: 
            - "MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD"
        volumes:
            - "$PWD/db_data:/var/lib/mysql"
        networks: 
            - net
networks: 
    net: